/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.8/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    id("java")
    id("application")
    id("com.github.johnrengelman.shadow") version "7.1.0"
}

repositories {
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    implementation(libs.guava)

    implementation("org.jfree:jfreechart:1.5.3")

    implementation("com.fasterxml.jackson.core:jackson-databind:2.12.5")

    compileOnly("org.projectlombok:lombok:1.18.22")
    annotationProcessor("org.projectlombok:lombok:1.18.22")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(11)
    }
}

application {
    // Define the main class for the application.
    mainClass = "com.week_8and9.FibonacciCalculator"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

tasks {
    jar{
        manifest {
            attributes(
                "Main-Class" to "com.week_8and9.FibonacciCalculator"
            )
        }
    }

    shadowJar {
        archiveBaseName.set("fibonacci-gradle-app")
        archiveVersion.set("v1.0")
    }
}

tasks.clean {
    delete("build") // Очищаем директорию build при выполнении clean
}